image: gitpod/workspace-full
vscode:
  extensions:
    # CMake tool
    - ms-vscode.cmake-tools
    # GDB Debug
    - webfreak.debug
    # C/C++ Code completion
    - llvm-vs-code-extensions.vscode-clangd
