image: gitpod/workspace-full

pipelines:
  default:
    - step:
        name: Build
        script:
          - cmake --config Debug --target hello -S . -B build
          - cmake --build build -- -j
        artifacts:
          - build/hello
    - step:
        name : Run
        script:
          - build/hello
